#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# --diff-filter=d excludes deleted files, which would otherwise cause the check to err out.
UNSTAGED_CHANGES_IN_STAGED_FILES=$(git diff --name-only --cached --diff-filter=d | xargs -r git diff --name-only)


if [ ! -z "$UNSTAGED_CHANGES_IN_STAGED_FILES" ]; then
    echo "\033[33mThere are unstaged changes in the following staged files:\033[0m"
    echo "$UNSTAGED_CHANGES_IN_STAGED_FILES" | while read line; do
      echo " - $line"
    done
    echo ""
    echo "This is a problem because the pre-commit hook formats all staged changes\
 and adds those formatting adjustments to the staged files.\
 If you include un-staged changes on top of staged files, there will likely be conflicts.\
 So it is not allowed."
    echo ""
    exit 1
fi

if ! git diff --quiet; then
  echo "Stashing unstaged changes..."
  git stash save --keep-index --include-untracked
  STASH_CREATED=1
fi

echo "Formatting staged changes..."

npm run format
npm run css-types

git add .

npm run test

if [ "$STASH_CREATED" = 1 ]; then
  echo "Popped stashed, unstaged changes..."
  git stash pop
fi
